version: '3.8'
services:
  PharmaPlus:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12345
      - MSSQL_PID=Developer
    ports:
      - "14331:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql-network

volumes:
  sqlserver_data:

networks:
  sql-network:
    driver: bridge