version: '3.8'
services:
  PharmaPlus:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Black3363#
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password12345" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  sqlserver_data: